@startuml componentDiagram

component  " <<component>>\n Biblioteca" {
    portin p1
    portout p2
    component "         <<component>>\nBiblioteca UI" as UI
    component "               <<component>>\n Biblioteca BackOffice" as Backend
    interface "API BIB" as API
    
 
}

database "Base de Dados da Biblioteca" as BD {

}

UI -- p1
UI -- API
Backend --> API
Backend -- p2
p2- BD

@enduml