@startuml deploymentDiagram

node "Servidor: BIB_UI" as FE{
   component "         <<component>>\Biblioteca UI" as UI
  
}

node "Servidor: BIB_BO" as BO {
  component "               <<component>>\n Biblioteca Backoffice" as Backoffice
}

database "Base de Dados da Biblioteca" as BD {

}

FE--BO : http/s
BO--BD : TCP/IP

@enduml